### PR TITLE
fix crash/exit instead of returning error for unsupported mappers

### LINKED ISSUE #4186: Crash when loading Digital Devil Story: Megami Tensei
### Summary
Bizhawk instantly closes when loading the Famicom game Digital Devil Story: Megami Tensei. This is a ROM I dumped myself using an OSCR, the MD5 hash (99FBA6D02D110914C09A16E13F488CB5) matches a known verified dump in no-intro.org's database. 

### Repro
1. Launch BizHawk
2. File -> Open ROM..., select "Digital Devil Story - Megami Tensei (Japan).nes"

### Output
On Windows, no error message is presented. On Linux, the following is logged to the console: 
```
ROM was not a multiple of 1024 bytes, and not a recognized header size: 16. Assume it's purely ROM data.
Game was not in DB. CRC: 682C4603 MD5: 99FBA6D02D110914C09A16E13F488CB5
D012E60C1C706FE60187A9DFA6A3CC5B071A348F
Could not find mapper for code: 12
```
It is worth noting that the ROM does in fact have a 16-byte iNES header, and is 262160 bytes in size (16 byte header plus 256 * 1024 bytes).

### Host env.
* BizHawk 2.10 on Windows 11 23H2
* BizHawk 2.10 on antiX Linux (Debian-based) 
* Current dev build dated Jan 7, 2025 exhibits the same behavior

This same ROM works in BizHawk 2.9.1. The emulator shows a green check mark for ROM verification status and shows this output when the check mark is clicked:
```
Identified from BootGod's database

------
BEGIN NES rom analysis:
Found iNES header:
pr=128,ch=128,wr=8,vr=0,ba=0,pa=1|0,brd=MAPPER076,sys=
Found iNES V2 header:
pr=128,ch=128,wr=0,vr=0,ba=0,pa=1|0,brd=MAPPER0076-00,sys=NES-NTSC
Since this is iNES we can (somewhat) confidently parse PRG/CHR banks to hash.
headerless rom hash: SHA1:F60102AB3B1470ECFBB7FE31FD9392E6B4BFBFBA
headerless rom hash:  MD5:D99BDC0B1E6D146D593E933F74BBE4D3
Could not locate game in bizhawk gamedb
Chose board from nescartdb:
pr=128,ch=128,wr=0,vr=0,ba=0,pa=1|0,brd=NAMCOT-3446,sys=Famicom
Final game detection results:
pr=128,ch=128,wr=0,vr=0,ba=0,pa=1|0,brd=NAMCOT-3446,sys=Famicom
"Megami Tensei: Digital Devil Story"
Implemented by: class Mapper076
END NES rom analysis
------
```

### PR DESCRIPTION
**Pull request by Morilli**
Should fix https://github.com/TASEmulators/BizHawk/issues/4186.

BizHawk-side diff:
```diff
diff --git a/quicknes/bizinterface.cpp b/quicknes/bizinterface.cpp
index 81249c60d..29a7cbfee 100644
--- a/quicknes/bizinterface.cpp
+++ b/quicknes/bizinterface.cpp
@@ -37,10 +37,9 @@ QN_EXPORT void qn_delete(quickerNES::Emu *e)
 	free(e);
 }
 
-QN_EXPORT const char *qn_loadines(quickerNES::Emu *e, const void *data, int length)
+QN_EXPORT const char *qn_loadines(quickerNES::Emu *e, const uint8_t *data, int length)
 {
-	e->load_ines((const uint8_t*)data);
-	return 0;
+	return e->load_ines(data);
 }
 
 QN_EXPORT const char *qn_set_sample_rate(quickerNES::Emu *e, int rate)
```

### CODE REVIEW

File: source/quickerNES/core/core.hpp [hunk 1]
```diff
@@ -153,7 +153,7 @@ class Core : private Cpu
     if (mapper == nullptr)
     {
       fprintf(stderr, "Could not find mapper for code: %u\n", mapperCode);
-      exit(-1);
+			return "Unsupported mapper";
```
Comment (CasualPokePlayer) [inline source/quickerNES/core/core.hpp]: Seems to be weird whitespace changes along with tabbing being used where the source files are using spaces for tabs.

Comment (Morilli) [reply source/quickerNES/core/core.hpp]: Must have been because I was editing from inside the submodule.
